/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './Components/**/*.razor',
    './wwwroot/**/*.html',
    './**/*.cshtml',
  ],
  safelist: [
    'from-indigo-900',
    'via-purple-900',
    'to-pink-900',
    'bg-gradient-to-br',
    'backdrop-blur-sm',
    'text-white',
    'hover:bg-white/20',
    'hover:bg-white/30',
    'bg-white/10',
    'bg-white/20',
    'border-white/20',
    'border-white/40',
    'hover:border-white/40',
    'text-white/60',
    'text-white/80',
    'text-white/40',
    'shadow-2xl',
    'hover:shadow-2xl',
    'shadow-lg',
    'drop-shadow-2xl',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    'transition-all',
    'duration-200',
    'duration-300',
    'duration-500',
    'ease-out',
    'hover:scale-105',
    'hover:scale-110',
    'active:scale-95',
    'animate-pulse',
    'scale-110',
    'rotate-12',
    'scale-100',
    'transform',
    'group',
    'group-hover:opacity-100',
    'opacity-0',
    'absolute',
    'relative',
    'z-10',
    'inset-0',
    '-top-2',
    '-right-2',
    'w-7',
    'h-7',
    'h-40',
    'flex',
    'flex-col',
    'justify-center',
    'items-center',
    'bg-red-500',
    'hover:bg-red-600'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}